### ISSUE TITLE
[ENHANCEMENT] Proto file for package video-service

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/proto-file#12]
## Issue
Proto file for package video-service

## Task
- [x] rpc Get List Video
- [x] rpc Get Detail Video
- [x] rpc Create new Video
- [x] rpc Update Video
- [x] rpc Delete a Video
- [x] rpc Get Statistic Video

**Comment by setiadijoe** [comment]
update message Create New Video, add field actor
